name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://Adrsh03:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Adrsh03/DocuMind
          git push hf main --force
